# Generated by Django 3.1.7 on 2021-04-06 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(default='')),
                ('mark', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Tasked', 'Tasked'), ('Finished', 'Finished'), ('Failed', 'Failed')], default='Tasked', max_length=50)),
                ('task_load', models.FileField(default='', upload_to='txts')),
                ('desc_for_mark', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_expiry', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_homework', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
