# Generated by Django 3.1.7 on 2021-04-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='task_load',
            field=models.FileField(default='', null=True, upload_to='txts'),
        ),
    ]
